name: Release-builds

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: '0'
            
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
      - name: Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install click
      
      - name: Freeze CLI
        run: |
          cd tools/PBuild
          pyinstaller pbuild.py
      
      - name: Zip
        run: |
          cd tools/PBuild/dist
          zip -r PBuild_linux.zip pbuild
                   
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.BIG_SECRET_NAME }}"
          automatic_release_tag: "${{ matrix.os }}"
          prerelease: true
          title: "${{ steps.date.outputs.date }}a-${{ matrix.os }}"
          files: "tools/PBuild/dist/PBuild_${{ matrix.os }}.zip"
